# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]

method = "squash"

# dont_wait_on_status_checks = ["ecosystem-lint", "scripts-lint"]

automerge_label = "merge"

block_on_neutral_required_check_runs = true