queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=scripts-lint
      - check-success=ecosystem-lint
    actions:
      queue:
        name: default
