queue_rules:
  - name: default
    speculative_checks: 10
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=ecosystem-lint
      - label=automerge
    actions:
      queue:
        name: default
