name: "Lint+Test"
on:
  pull_request:
    branches:
      - stuff5
  push:
    branches:
      - main
      - devnet
      - testnet
      - auto
      - canary
      - staging
      - stuff5

jobs:
  scripts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install shellcheck --assume-yes --no-install-recommends
      - run: shellcheck scripts/dev_setup.sh
      - run: shellcheck scripts/dockerhub_prune.sh
      - run: shellcheck scripts/weekly-dep-report.sh

  # e2e-test:
  #   if: github.event_name == 'push' 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: sleep 120 && crash

  ecosystem-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      # install packages for examples
      - run: cd ./ecosystem/typescript/sdk/examples/typescript && yarn install
      - run: cd ./ecosystem/typescript/sdk/examples/javascript && yarn install

      # - if: ${{ github.ref != 'refs/heads/feature5' }}
      #   run: failthing
      # Run package build+lint + tests
      - run: cd ./ecosystem/typescript/sdk && yarn install
      - run: cd ./ecosystem/typescript/sdk && yarn lint
      - run: cd ./ecosystem/typescript/sdk && yarn fmt:check
      # Run typescript indexer server linting
      - run: cd ./ecosystem/indexer-server/typescript && yarn install
      - run: cd ./ecosystem/indexer-server/typescript && yarn lint
