name: "Sync PR to Branch"

# on:
#   pull_request:
#     types: [labeled, opened, synchronize, reopened]


jobs:
  sync-branch:
    name: Update test branch
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
