name: "Top Of Queue Check"
on:
  check_run:
    types: [created]

jobs:
  scripts-lint:
    runs-on: ubuntu-latest

    steps:
      - run: echo $NAME
        env:
          NAME: ${{ github.event.check_run.name }}
