name: "Top Of Queue Check"
on:
  check_run:
    types: [created]

jobs:
  scripts-lint:
    runs-on: ubuntu-latest

    steps:
      - run: jq "$NAME"
        env:
          NAME: ${{ toJson(github.event.check_run) }}
